import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Box, Flex, FormControl, FormLabel, Heading, Text, Input, VStack, HStack, Checkbox, Button} from '@chakra-ui/react'
const BgImg = require('../assets/signup-bg.png')

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Flex w="full">
          <Box position={'relative'} display={['none','block']} className="w-1/2 h-screen bg-gray-200" >
            <Box display={['none','block']}>
              <Image src={BgImg}  className="h-full w-full z-10" alt="woman smiling"/>
            </Box>
            <Box padding={'12rem'} position={'absolute'} bottom={0} zIndex={200}>
              <Text  color={"white"} className="text-xl">
                Building exceptional services with Back Office Support and Business Perfomance
              </Text>
            </Box>
          </Box>
          <Box padding={[3, 10]} className="w-full md:w-1/2">
            <Box mb={10}>
              <Heading fontSize={20}>Create Account</Heading>
              <Text color={'#82869A'}>Build and exceptional business</Text>
            </Box>
            <form className='w-full'>
              <VStack spacing={9}>
                <HStack spacing={5} w="full">
                  <FormControl>
                    <FormLabel htmlFor='firstname' color={'#82869A'} fontSize={13}>First Name</FormLabel>
                    <Input id='firstname' type='text' variant="flushed" placeholder='Enter your first name' _placeholder={{ fontsize: '3' }}/>
                  </FormControl>
                  <FormControl>
                    <FormLabel htmlFor='lastname' color={'#82869A'} fontSize={13}>Last Name</FormLabel>
                    <Input id='lastname' type='text' variant="flushed" placeholder='Enter your last name'/>
                  </FormControl>
                </HStack>
                <FormControl>
                  <FormLabel htmlFor='phonenumber' color={'#82869A'} fontSize={13}>Phone Number</FormLabel>
                  <Input id='phonenumber' type='phone' variant="flushed" placeholder='Enter your phone number'/>
                </FormControl>
                <FormControl>
                  <FormLabel htmlFor='email' color={'#82869A'} fontSize={13}>Email Address</FormLabel>
                  <Input id='email' type='email' variant="flushed" placeholder='Enter your email'/>
                </FormControl>
                <FormControl>
                  <FormLabel htmlFor='password' color={'#82869A'} fontSize={13}>Password</FormLabel>
                  <Input id='password' type='password' variant="flushed" placeholder='Enter your password'/>
                </FormControl>

                <Flex justifyContent={'space-between'} w="full">
                  <Checkbox color={'#82869A'} fontSize={15}>Remember me</Checkbox>

                  <Link href='/' className="text-red-900" fontSize={13}>Forgot Password?</Link>
                </Flex>

                <Link href='/dashboard'>
                  <Button
                    // isLoading
                    loadingText='Signing you in'
                    colorScheme='blue'
                    variant='solid'
                    w={'full'}
                    dropShadow={true}
                    paddingY={7}
                  >
                    Sign up
                  </Button>
                </Link>

                <HStack spacing={3}>
                  <Checkbox color={'#82869A'} fontSize={15}>Got an Account?</Checkbox>

                  <Link href='/' className="text-red-900" fontSize={13}>Sign In</Link>
                </HStack>

              </VStack>
            </form>
          </Box>
        </Flex>
      </main>
    </div>
  )
}


const styles = {
  signup: {
    backgroundImage: `url(${BgImg})`
  }
}
